export enum AUTH_TYPES {
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT'
}

export enum RELIABLE_PERFORMANCE_TYPES {
    GOALKEEPER = 'GOALKEEPER',
    LOWBLOCK = 'LOWBLOCK',
    MIDBLOCK = 'MIDBLOCK',
    HIGHBLOCK = 'HIGHBLOCK',
    QUIT = ''
}